version: '3.3'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"

    volumes:
      - ./router.conf:/etc/nginx/conf.d/default.conf
      - ./static_files:/var/html/static/

