version: '3.3'

volumes:
  postgres_data:

services:
  web:
    build: .
    restart: always
    command: gunicorn shortenner.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./shortenner/.env.production

